AppGenerator/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

app_name = 'app_generator'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^backend-form/$', views.backendForm, name='backendForm'),
    url(r'^search$', views.searchProjectFolder, name="searchProject"),
    url(r'^setup/download/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^setup/(?P<frontend>\w+)-(?P<backend>\w+)', views.setup, name='setup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hackathon_Project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from AppGenerator import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^',include('AppGenerator.urls',namespace='app_generator')),
]


    

AppGenerator/models.py
from django.db import models

class Project(models.Model):
    projectID = models.IntegerField(primary_key=True, default=0)
    projectFolder = models.FileField(upload_to='media')
    frontend = models.CharField(max_length=30)
    backend = models.CharField(max_length=30)

    def __str__(self):
        return self.frontend + " <=> " + self.backend

class Backend(models.Model):
    bId = models.IntegerField(primary_key=True, default=0)
    bName = models.CharField(max_length=30)

    def __str__(self):
        return self.bName

class Frontend(models.Model):
    fId = models.IntegerField(primary_key=True, default=0)
    fName = models.CharField(max_length=30)
    backends = models.ManyToManyField(to=Backend)

    def __str__(self):
        return self.fName

AppGenerator/forms.py
from email.policy import default
from logging import PlaceHolder
from django import forms
from .models import Frontend, Backend

class FrontendForm(forms.Form):
    fChoices = tuple([("","Select Frontend stack")] + [(x.fName, x.fName) for x in Frontend.objects.all()])
    frontend = forms.ChoiceField(choices=fChoices, label="Frontend Framework", initial="")

AppGenerator/views.py
from http.client import HTTPResponse
# from msilib.schema import File
from multiprocessing import context
from turtle import back
from winreg import REG_QWORD
from django.shortcuts import render,redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.conf import settings
from . import forms 
from .models import Project, Frontend, Backend
import os
import shutil

fInput = ""
bInput = ""

def index(request):
    form = forms.FrontendForm()
    context = {
        'form': form,
    }
    return render(request, 'AppGenerator/index1.html', context)

def backendForm(request):
    global fInput
    if request.method=="POST":
        form = forms.FrontendForm(request.POST)
        if form.is_valid():
            fName = form.cleaned_data['frontend']
            fInput = fName
            fObj = Frontend.objects.get(fName=fInput)
            bList = fObj.backends.all()
    context = {
        'choices': bList
    }
    return render(request, 'AppGenerator/index2.html', context)

def searchProjectFolder(request):
    if request.method=="POST":
        if request.POST.get("backend") not in ["",None]:
            global bInput, fInput
            bInput = request.POST.get("backend")
            
            fInput = "_dot_".join(fInput.split("."))
            fInput = "".join(fInput.split(" "))
            bInput = "_dot_".join(bInput.split("."))
            return HttpResponseRedirect("/setup/"+fInput+"-"+bInput) 
    else:
        return HttpResponseRedirect("/backend-form")      

def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT,path)
    if os.path.exists(file_path):
        with open(file_path,'rb') as fh:
            response = HttpResponse(fh.read(), content_type='attachment/zip')
            response['Content-Disposition'] = 'inline;filename=' + os.path.basename(file_path)
            return response
    raise Http404


def setup(request, frontend, backend):
    docFileName = frontend + "-" + backend + ".txt"
    documentation = []
    with open(os.path.join(os.path.abspath("./static/docs/"),docFileName), "r") as f:
        for line in f.readlines():
            line = "".join(line.split("\t"))
            line = "".join(line.split("\n"))
            documentation .append(line)
    f.close()
    
    frontend = ".".join(frontend.split("_dot_"))
    backend = ".".join(backend.split("_dot_"))
    
    project = Project.objects.get(frontend=frontend, backend=backend)
    context = {
        'project': project,
        'documentation': documentation
    }
    return render(request, 'AppGenerator/setup.html', context)

templates/AppGenerator/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Generator</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/styles.css">
</head>
<body>
    <div class="container-fluid main-div">
        <div class="header">
            <h2 class="heading">Skeleton Code Generator</h2>
            <p class="app-info">Download Boiler plate code of your web application within seconds.</p>
        </div>
        <!-- <div class="cards">
            <div class="card col-lg-6 col-md-6">
                <img src="" alt="" class="card-img">
                <h6 class="card-title">1. Select a Frontend Framework</h6>
                <p class="card-info">Choose one technology that you like to use for Frontend of your project.</p>
            </div>
            <div class="card col-lg-6 col-md-6">
                <img src="" alt="" class="card-img">
                <h6 class="card-title">2. Select a Backend Framework</h6>
                <p class="card-info">You will be displayed a list of Backend Frameworks that are compatible to use with the Frontend you chose.</p>
            </div>
            <div class="card col-lg-6 col-md-6">
                <img src="" alt="" class="card-img">
                <h6 class="card-title">3. Read the Documentation</h6>
                <p class="card-info">Go through the detailed documentation of installation and execution process of your web application.</p>
            </div>
            <div class="card col-lg-6 col-md-6">
                <img src="" alt="" class="card-img">
                <h6 class="card-title">4. Customize the project</h6>
                <p class="card-info">Customize the downloaded project folder according to your requirements.</p>
            </div>
        </div> -->
        <div class="input-form">
            <form method="POST" action="{% url 'app_generator:backendForm' %}">
                {% csrf_token %}
                <div class="inline">
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-outline-primary" name="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
    <!-- <img src="../../static/images/background.jpg" alt="main-img" class="main-img"> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="../../static/js/index.js"></script>
</body>
</html>

templates/AppGenerator/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Generator</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/styles.css">
</head>
<body>
    <div class="main-div">
        <div class="header">
            <h2 class="heading">Skeleton Code Generator</h2>
            <p class="app-info">Download Boiler plate code of your web application within seconds.</p>
        </div>
        <div class="container">
            <div class="input-form">
                <form action="{% url 'app_generator:searchProject' %}" method="POST">
                    {% csrf_token %}
                    <label for="backend">Backend Framework:</label>
                    <select name="backend" id="backend">
                    {% for b in choices %}
                        <option value="{{ b.bName }}">{{ b.bName }}</option>
                    {% endfor %}
                    </select>
                    <div class="btn-group inline btns" role="group">
                        <button type="button" class="btn btn-outline-danger"><a href="{% url 'app_generator:index' %}">Back</a></button>
                        <button type="submit" class="btn btn-outline-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="../../static/js/index.js"></script>
</body>
</html>

templates/AppGenerator/setup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ project.frontend }} <-> {{ project.backend }}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/setup.css">
</head>
<body>
    <h3 class="title">{{ project.frontend }} <-> {{ project.backend }}</h3>
    <div class="container-fluid documentation">
        {% for l in documentation %}
            {% if l.0 == '$' %}
                <p class="doc-line terminal">{{ l }}</p>
            {% else %}
                <p class="doc-line">{{ l }}</p>
            {% endif %}
        {% endfor %}
    </div>
    <button class="download btn btn-success"><a href="download/{{ project.projectFolder }}">Download</a></button>
</body>
</html>